### ISSUE TITLE
Catalyst app for macOS

### ISSUE THREAD

**Issue by albertputinjobs** [kashkashio/PopcornTimeTV#13]
Please create a macOS version of this app using project catalyst

**Comment by kashkashio** [comment]
There is an official version for macos.. why would we do that?
A Waste of time.
https://popcorntime.app/

**Comment by albertputinjobs** [comment]
Apple is going to introduce arm macbooks....That's why I was saying about it

**Comment by kashkashio** [comment]
Oh i see. well lets wait for that :)
