### ISSUE TITLE
tvOS subtitles language selector being closed

### ISSUE THREAD

**Issue by kashkashio** [kashkashio/PopcornTimeTV#2]
When trying to select a subtitle when playing a movie on tvos the screen closed right after being open and makes language selection unavailable.

There is a workaround - go to settings and set a default language.

To be fixed..

**Comment by kashkashio** [comment]
Fixed.

**Comment by wildberto** [comment]
Can you upload the TVos deb file?

**Comment by kashkashio** [comment]
Deb file? U mean the packaged ipa for tvos?

**Comment by kashkashio** [comment]
Fixed
