### ISSUE TITLE
On iOS 13.3.1 app crash when try to load on real device.

### ISSUE THREAD

**Issue by ervinpepic** [kashkashio/PopcornTimeTV#5]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

App should start when press build and run.

#### Actual Behaviour

When app start this error showed i debugger
```
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire

```
```
Thread 1: signal SIGABRT

```
#### Steps to reproduce the behaviour

1. Open PopcornTime.xcworkspace
2. Build and run and then error happened
3. I use some research and found that on official Alamofire page error was reported. link is

```
https://github.com/Alamofire/Alamofire/issues/3051

```

Conclusion:
I think from now we need a paid apple developer account... If somebody can fix this please tell us!

**Comment by kashkashio** [comment]
Hi Thanks for posting it,
I’m actually working with my apple developer and building directly on the devices and it works perfectly on tvos ipad and iphone

You are installing it with the ipa through the side loader?

**Comment by ervinpepic** [comment]
I don't have paid Apple Developer account, and ...that's all problem I think...

**Comment by saveyourskin** [comment]
I´m having the same problem, i have the latest version of the original repository, installed via KodiTVBox.ca signing service,   it was working flawlessly just before my girlfriend accepted the TvOS update by mistake.
but now the app just crashes when i try to load it.  does the latest .ipa from this repository work with this TVOS update?

**Comment by mananhiteshkataria** [comment]
this issue is because of ios 13.3.1 and apple needs to fix it almost everyone sideloading is pissed at this point waiting for a jailbreak to be released heard a lot of complaints about it in the appdb forums thats why rickpactor hasnt been updated too
paid accounts should not have an issue as they can make their own license
